name=input("Digite um funcionário: ")
empresa=input("Digite a instituição: ")
qtde_fun=int(input("Digite a qtde de funcionários: "))
mediaMen=float(input("Digite a média da mensalidade: "))
print(name+ " trabalha na empresa " +empresa)
print("Possui: ", qtde_fun, "funcionários")
print("A média da mensalidade é de: "+ str(mediaMen))
print("=================== Verifique os tipos de dados abaixo================")
print("O tipo de dado da variável [name] é : ", type (name))
print("O tipo de dado da variável [empresa] é : ", type (empresa))
print("O tipo de dado da variável [qtde_fun] é : ", type (qtde_fun))
print("O tipo de dado da variável [mediaMen] é : ", type (mediaMen))